#!/usr/bin/env python

import pandas as pd
import sys

if len(sys.argv) != 3:
    print("Usage: input.xlsx output.vcf")
    sys.exit(1)

_, in_file, out_file = sys.argv

print('Reading ' + in_file + '...')
variants_df = pd.read_excel(in_file, sheet_name='rawdata')

print('Writing variants to VCF...')
with open(out_file, 'w') as f:
    f.write('##fileformat=VCFv4.2\n')
    f.write('#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')
    for (ix, line) in variants_df.sort_values(['VARICARTA_Chr', 'VARICARTA_Start']).iterrows():
        f.write('\t'.join(['chr' + str(line.VARICARTA_Chr), str(line.VARICARTA_Start), str(line["Child ID"]), line.VARICARTA_Ref, line.VARICARTA_Alt, '.', '.', '.']) + '\n')
